# Generated by Django 3.1.7 on 2021-03-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210308_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='profile',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='from_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='chat.profile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='chat.profile'),
        ),
    ]
