# Generated by Django 3.1.7 on 2021-03-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210308_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='chat.FriendRequest'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='chat.profile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='chat.profile'),
        ),
    ]
