# Generated by Django 3.1.7 on 2021-03-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210308_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='request_status',
        ),
    ]
