# Generated by Django 3.1.7 on 2021-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_friendrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='online', max_length=15),
            preserve_default=False,
        ),
    ]
