# Generated by Django 3.1.7 on 2021-04-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
